---
# Copyright (C) 2020 Robin Schneider <ypid@riseup.net>
# Copyright (C) 2020 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Deploy and manage WireGuard
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_service_wireguard' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: etc_services
      tags: [ 'role::etc_services', 'skip::etc_services' ]
      etc_services__dependent_list:
        - '{{ wireguard__etc_services__dependent_list }}'

    - role: ferm
      tags: [ 'role::ferm', 'skip::ferm' ]
      ferm__dependent_rules:
        - '{{ wireguard__ferm__dependent_rules }}'

    - role: wireguard
      tags: [ 'role::wireguard', 'skip::wireguard' ]
